// <auto-generated />
using System;
using FarmerAPI.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FarmerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525230633_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FarmerAPI.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Amount = "500",
                            Contact = "5091112233",
                            CreateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CropType = "Wheat",
                            Description = "High-quality hard red winter wheat, perfect for milling or animal feed.",
                            ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Spokane, WA",
                            Name = "farmer1@example.com",
                            Price = "15",
                            Status = "Active",
                            Title = "Fresh Wheat - Bulk Sale",
                            UpdateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-0001-0001-0001-aaaaaaaaaaaa")
                        },
                        new
                        {
                            PostId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Amount = "300",
                            Contact = "5092223344",
                            CreateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CropType = "Corn",
                            Description = "Freshly harvested sweet corn, available for pickup or local delivery.",
                            ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Yakima, WA",
                            Name = "grower2@example.com",
                            Price = "8",
                            Status = "Active",
                            Title = "Sweet Corn - Fresh Harvest",
                            UpdateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-0002-0002-0002-aaaaaaaaaaaa")
                        },
                        new
                        {
                            PostId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Amount = "200",
                            Contact = "5093334455",
                            CreateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CropType = "Apples",
                            Description = "Certified organic Honeycrisp apples. Great for direct retail or farmers markets.",
                            ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Wenatchee, WA",
                            Name = "orchard3@example.com",
                            Price = "25",
                            Status = "Active",
                            Title = "Organic Honeycrisp Apples",
                            UpdateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-0003-0003-0003-aaaaaaaaaaaa")
                        },
                        new
                        {
                            PostId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Amount = "150",
                            Contact = "5094445566",
                            CreateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CropType = "Potatoes",
                            Description = "Idaho-style russet potatoes grown in Eastern Washington. Sold in 50lb bags.",
                            ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Moses Lake, WA",
                            Name = "potato4@example.com",
                            Price = "20",
                            Status = "Active",
                            Title = "Russet Potatoes - 50lb Bags",
                            UpdateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-0004-0004-0004-aaaaaaaaaaaa")
                        },
                        new
                        {
                            PostId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Amount = "400",
                            Contact = "5095556677",
                            CreateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CropType = "Tomatoes",
                            Description = "Firm Roma tomatoes ideal for sauces and canning. Wholesale pricing available.",
                            ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Tri-Cities, WA",
                            Name = "veggie5@example.com",
                            Price = "12",
                            Status = "Active",
                            Title = "Roma Tomatoes - Wholesale",
                            UpdateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-0005-0005-0005-aaaaaaaaaaaa")
                        },
                        new
                        {
                            PostId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Amount = "600",
                            Contact = "5096667788",
                            CreateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CropType = "Soybeans",
                            Description = "Certified non-GMO soybeans. Suitable for food-grade and feed markets.",
                            ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Pullman, WA",
                            Name = "crops6@example.com",
                            Price = "18",
                            Status = "Active",
                            Title = "Non-GMO Soybeans",
                            UpdateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-0006-0006-0006-aaaaaaaaaaaa")
                        },
                        new
                        {
                            PostId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Amount = "100",
                            Contact = "5097778899",
                            CreateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CropType = "Strawberries",
                            Description = "Vine-ripened strawberries. Pick-up only at the farm. Call ahead to schedule.",
                            ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Bellingham, WA",
                            Name = "berry7@example.com",
                            Price = "30",
                            Status = "Active",
                            Title = "Fresh Strawberries - Pick Up Only",
                            UpdateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-0007-0007-0007-aaaaaaaaaaaa")
                        },
                        new
                        {
                            PostId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Amount = "250",
                            Contact = "5098889900",
                            CreateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CropType = "Carrots",
                            Description = "Pre-washed baby carrots ready for restaurant and grocery supply chains.",
                            ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Olympia, WA",
                            Name = "garden8@example.com",
                            Price = "10",
                            Status = "Active",
                            Title = "Baby Carrots - Restaurant Supply",
                            UpdateDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-0008-0008-0008-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("FarmerAPI.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4ae173ee-436c-4aa1-bb8a-30fa0f2e1847",
                            CreateAt = new DateTime(2026, 5, 25, 23, 6, 33, 758, DateTimeKind.Utc).AddTicks(8333),
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEBOh9VDIsWRjKXEn6TmrMlrCPIGqL6m64pzc50apkGYYdhvGCvLeB+bvIv5Zjpg4nQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "05f816ee-6050-41d6-9911-fec41f58fdff",
                            TwoFactorEnabled = false,
                            UpdateAt = new DateTime(2026, 5, 25, 23, 6, 33, 758, DateTimeKind.Utc).AddTicks(8334),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FarmerAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FarmerAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmerAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FarmerAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
