// <auto-generated />
using System;
using FarmerAPI.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmerAPI.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new { PostId = new Guid("11111111-1111-1111-1111-111111111111"), Title = "Fresh Wheat - Bulk Sale", Price = "15", CropType = "Wheat", Amount = "500", Location = "Spokane, WA", Contact = "5091112233", Description = "High-quality hard red winter wheat, perfect for milling or animal feed.", CreateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), UpdateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, DateTimeKind.Utc), Name = "farmer1@example.com", Status = "Active", UserId = new Guid("aaaaaaaa-0001-0001-0001-aaaaaaaaaaaa") },
                        new { PostId = new Guid("22222222-2222-2222-2222-222222222222"), Title = "Sweet Corn - Fresh Harvest", Price = "8", CropType = "Corn", Amount = "300", Location = "Yakima, WA", Contact = "5092223344", Description = "Freshly harvested sweet corn, available for pickup or local delivery.", CreateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), UpdateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, DateTimeKind.Utc), Name = "grower2@example.com", Status = "Active", UserId = new Guid("aaaaaaaa-0002-0002-0002-aaaaaaaaaaaa") },
                        new { PostId = new Guid("33333333-3333-3333-3333-333333333333"), Title = "Organic Honeycrisp Apples", Price = "25", CropType = "Apples", Amount = "200", Location = "Wenatchee, WA", Contact = "5093334455", Description = "Certified organic Honeycrisp apples. Great for direct retail or farmers markets.", CreateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), UpdateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, DateTimeKind.Utc), Name = "orchard3@example.com", Status = "Active", UserId = new Guid("aaaaaaaa-0003-0003-0003-aaaaaaaaaaaa") },
                        new { PostId = new Guid("44444444-4444-4444-4444-444444444444"), Title = "Russet Potatoes - 50lb Bags", Price = "20", CropType = "Potatoes", Amount = "150", Location = "Moses Lake, WA", Contact = "5094445566", Description = "Idaho-style russet potatoes grown in Eastern Washington. Sold in 50lb bags.", CreateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), UpdateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, DateTimeKind.Utc), Name = "potato4@example.com", Status = "Active", UserId = new Guid("aaaaaaaa-0004-0004-0004-aaaaaaaaaaaa") },
                        new { PostId = new Guid("55555555-5555-5555-5555-555555555555"), Title = "Roma Tomatoes - Wholesale", Price = "12", CropType = "Tomatoes", Amount = "400", Location = "Tri-Cities, WA", Contact = "5095556677", Description = "Firm Roma tomatoes ideal for sauces and canning. Wholesale pricing available.", CreateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), UpdateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, DateTimeKind.Utc), Name = "veggie5@example.com", Status = "Active", UserId = new Guid("aaaaaaaa-0005-0005-0005-aaaaaaaaaaaa") },
                        new { PostId = new Guid("66666666-6666-6666-6666-666666666666"), Title = "Non-GMO Soybeans", Price = "18", CropType = "Soybeans", Amount = "600", Location = "Pullman, WA", Contact = "5096667788", Description = "Certified non-GMO soybeans. Suitable for food-grade and feed markets.", CreateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), UpdateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, DateTimeKind.Utc), Name = "crops6@example.com", Status = "Active", UserId = new Guid("aaaaaaaa-0006-0006-0006-aaaaaaaaaaaa") },
                        new { PostId = new Guid("77777777-7777-7777-7777-777777777777"), Title = "Fresh Strawberries - Pick Up Only", Price = "30", CropType = "Strawberries", Amount = "100", Location = "Bellingham, WA", Contact = "5097778899", Description = "Vine-ripened strawberries. Pick-up only at the farm. Call ahead to schedule.", CreateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), UpdateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, DateTimeKind.Utc), Name = "berry7@example.com", Status = "Active", UserId = new Guid("aaaaaaaa-0007-0007-0007-aaaaaaaaaaaa") },
                        new { PostId = new Guid("88888888-8888-8888-8888-888888888888"), Title = "Baby Carrots - Restaurant Supply", Price = "10", CropType = "Carrots", Amount = "250", Location = "Olympia, WA", Contact = "5098889900", Description = "Pre-washed baby carrots ready for restaurant and grocery supply chains.", CreateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), UpdateDate = new DateTime(2026, 5, 23, 12, 0, 0, DateTimeKind.Utc), ExpireDate = new DateTime(9999, 12, 31, 0, 0, 0, DateTimeKind.Utc), Name = "garden8@example.com", Status = "Active", UserId = new Guid("aaaaaaaa-0008-0008-0008-aaaaaaaaaaaa") }
                    );
                });

            modelBuilder.Entity("FarmerAPI.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "62270ef0-206d-48fc-8eb5-e05a5b09cf8d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f333ca7c-00a6-4273-b1b5-e4900cb5aa18",
                            CreateAt = new DateTime(2025, 3, 7, 9, 12, 33, 329, DateTimeKind.Utc).AddTicks(8321),
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEFJrHqww3/sc87bnqXbsxuPgPlEQo+DHaozAwmfunfjBTJR74EdZk+YgsQaxHpTq8w==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "085f99dd-7fb7-4c64-a324-b69c7dd630c9",
                            TwoFactorEnabled = false,
                            UpdateAt = new DateTime(2025, 3, 7, 9, 12, 33, 329, DateTimeKind.Utc).AddTicks(8323),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2dc0e929-d7c0-4cd9-a73f-fe71b5b1d04c",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "62270ef0-206d-48fc-8eb5-e05a5b09cf8d",
                            RoleId = "2dc0e929-d7c0-4cd9-a73f-fe71b5b1d04c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FarmerAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FarmerAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmerAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FarmerAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
